# Generated by Django 5.0.14 on 2025-10-13 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianschedule',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.technicianprofile'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
