# Generated by Django 5.2.7 on 2025-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='rental_end_date',
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='rental_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
