# Generated by Django 5.2.7 on 2025-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_residentprofile DROP COLUMN IF EXISTS rental_end_date;",
            reverse_sql="ALTER TABLE accounts_residentprofile ADD COLUMN rental_end_date DATE NULL;",
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='rental_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
