# Generated by Django 5.2.7 on 2025-12-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='rooms_count',
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
