# Generated by Django 5.0.14 on 2025-10-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_roles'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='manual_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='manual_building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
