# Generated by Django 5.2.7 on 2025-10-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_residentprofile_rental_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='rooms_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
