# Generated by Django 5.2.7 on 2025-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_residentprofile_area_residentprofile_rooms_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='rental_duration',
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
