# Generated by Django 5.0.14 on 2025-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_admin_role'),
        ('accounts', '0004_residentprofile_manual_address_and_more'),
    ]

    operations = [
    ]
