# Generated by Django 5.2.7 on 2025-11-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_residentprofile_rental_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
