# Generated by Django 5.2.7 on 2025-10-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251014_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='resident_type',
            field=models.CharField(choices=[('owner', 'مالك'), ('tenant', 'مستأجر')], default='owner', max_length=20),
        ),
    ]
