# Generated by Django 5.2.7 on 2025-11-05 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_residentprofile_owner_alter_residentprofile_status'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='manual_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='manual_building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='owner_national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.unit'),
        ),
    ]
