# Generated by Django 5.2.7 on 2025-11-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_residentprofile_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='manual_address',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='manual_building_name',
        ),
    ]
