# Generated by Django 5.2.7 on 2025-11-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_residentprofile_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='owner_national_id',
        ),
    ]
