# Generated by Django 5.2.7 on 2025-11-28 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('buildings', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('utilities', 'Utilities'), ('prepaid', 'Prepaid'), ('fixed', 'Fixed'), ('misc', 'Misc')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFixed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_day', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('union_head', 'Union Head'), ('direct_person', 'Direct Person')], max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('sahl', 'Sahl'), ('fawry', 'Fawry'), ('wallet', 'Wallet')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.residentprofile')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PackageMisc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('deadline', models.DateField()),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePrepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water')], max_length=20)),
                ('manufacturer', models.CharField(max_length=255)),
                ('meter_number', models.CharField(max_length=100)),
                ('average_monthly_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageUtility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('internet', 'Internet')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('meter_number', models.CharField(max_length=100)),
                ('customer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_day', models.PositiveIntegerField()),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'unique_together': {('package', 'building')},
            },
        ),
    ]
