# Generated by Django 5.0.14 on 2025-10-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251014_1554'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.recurringpackage')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.residentprofile')),
            ],
        ),
    ]
