# Generated by Django 5.2.7 on 2025-11-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner_id',
            field=models.CharField(max_length=50),
        ),
    ]
