# Generated by Django 5.0.14 on 2025-10-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='ownership_contract',
        ),
        migrations.RemoveField(
            model_name='building',
            name='union_head_id',
        ),
        migrations.AddField(
            model_name='building',
            name='union_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to=settings.AUTH_USER_MODEL),
        ),
    ]
