# Generated by Django 5.2.7 on 2025-11-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='approved_by_id',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='union_head_id',
            new_name='union_head',
        ),
    ]
