# Generated by Django 5.0.14 on 2025-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_building_ownership_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='approval_status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
